spring.application.name=notification-service
server.port=8010

# --- База Данных ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

# --- Redis ---
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

# --- RabbitMQ ---
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# --- JWT ---
jwt.access.token.secret=${JWT_SECRET:asd}

# --- Swagger / SpringDoc ---
# Мы НЕ переопределяем пути вручную, чтобы работали дефолтные:
# /swagger-ui/index.html и /v3/api-docs

# Позволяет Swagger корректно работать за Ingress (определять https/http и домен)
server.forward-headers-strategy=framework
springdoc.swagger-ui.display-query-params=true

springdoc.swagger-ui.path=/api-docs/notification.html
# Сами данные (JSON) пусть лежат тут
springdoc.api-docs.path=/v3/api-docs

logging.level.com.matreshka.notification_service=INFO