apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: monitoring
data:
  matreshka_rules.yaml: |
    groups:
      - name: matreshka_metrics
        rules:
          - record: job:http_error_rate_percentage
            expr: |
              (sum by (app) (rate({app=~".+"} | regexp `status=(?P<status>5\d+)` [1m]))
              /
              sum by (app) (rate({app=~".+"} [1m]))) * 100