spring:
  application:
    name: video-converter-worker
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: "com.matreshka.video_converter_worker.delivery.broker.dto.VideoEvent"
        spring.json.trusted.packages: "com.matreshka.*"
  cloud:
    function:
      definition: consumeMessage
    stream:
      bindings:
        consumeMessage-in-0:
          destination: media-processor-process
          group: media-processor-process-group-v2
          content-type: application/json
        video-success-out-0:
          destination: media-processor-result
          content-type: application/json
        video-error-out-0:
          destination: media-processor-error
          content-type: application/json
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS}
          auto-create-topics: true
          auto-add-partitions: false
          configuration:
            metadata.max.age.ms: 600000
            request.timeout.ms: 60000
            session.timeout.ms: 30000
            client.id: video-converter-worker-client

aws:
  s3:
    region: ${AWS_S3_REGION}
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    endpoint: ${AWS_S3_ENDPOINT}
    bucket-name: ${AWS_S3_BUCKET_NAME}

server:
  port: 8020