
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Advert: 'Advert',
  Pictures: 'Pictures',
  Services: 'Services',
  WorkPeriod: 'WorkPeriod',
  Video: 'Video'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "advert" | "pictures" | "services" | "workPeriod" | "video"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Advert: {
      payload: Prisma.$AdvertPayload<ExtArgs>
      fields: Prisma.AdvertFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AdvertFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AdvertFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>
        }
        findFirst: {
          args: Prisma.AdvertFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AdvertFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>
        }
        findMany: {
          args: Prisma.AdvertFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>[]
        }
        create: {
          args: Prisma.AdvertCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>
        }
        createMany: {
          args: Prisma.AdvertCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AdvertCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>[]
        }
        delete: {
          args: Prisma.AdvertDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>
        }
        update: {
          args: Prisma.AdvertUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>
        }
        deleteMany: {
          args: Prisma.AdvertDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AdvertUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AdvertUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>[]
        }
        upsert: {
          args: Prisma.AdvertUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdvertPayload>
        }
        aggregate: {
          args: Prisma.AdvertAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAdvert>
        }
        groupBy: {
          args: Prisma.AdvertGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AdvertGroupByOutputType>[]
        }
        count: {
          args: Prisma.AdvertCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AdvertCountAggregateOutputType> | number
        }
      }
    }
    Pictures: {
      payload: Prisma.$PicturesPayload<ExtArgs>
      fields: Prisma.PicturesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PicturesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PicturesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>
        }
        findFirst: {
          args: Prisma.PicturesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PicturesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>
        }
        findMany: {
          args: Prisma.PicturesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>[]
        }
        create: {
          args: Prisma.PicturesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>
        }
        createMany: {
          args: Prisma.PicturesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PicturesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>[]
        }
        delete: {
          args: Prisma.PicturesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>
        }
        update: {
          args: Prisma.PicturesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>
        }
        deleteMany: {
          args: Prisma.PicturesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PicturesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PicturesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>[]
        }
        upsert: {
          args: Prisma.PicturesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PicturesPayload>
        }
        aggregate: {
          args: Prisma.PicturesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePictures>
        }
        groupBy: {
          args: Prisma.PicturesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PicturesGroupByOutputType>[]
        }
        count: {
          args: Prisma.PicturesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PicturesCountAggregateOutputType> | number
        }
      }
    }
    Services: {
      payload: Prisma.$ServicesPayload<ExtArgs>
      fields: Prisma.ServicesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ServicesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ServicesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>
        }
        findFirst: {
          args: Prisma.ServicesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ServicesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>
        }
        findMany: {
          args: Prisma.ServicesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>[]
        }
        create: {
          args: Prisma.ServicesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>
        }
        createMany: {
          args: Prisma.ServicesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ServicesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>[]
        }
        delete: {
          args: Prisma.ServicesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>
        }
        update: {
          args: Prisma.ServicesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>
        }
        deleteMany: {
          args: Prisma.ServicesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ServicesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ServicesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>[]
        }
        upsert: {
          args: Prisma.ServicesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicesPayload>
        }
        aggregate: {
          args: Prisma.ServicesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateServices>
        }
        groupBy: {
          args: Prisma.ServicesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServicesGroupByOutputType>[]
        }
        count: {
          args: Prisma.ServicesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServicesCountAggregateOutputType> | number
        }
      }
    }
    WorkPeriod: {
      payload: Prisma.$WorkPeriodPayload<ExtArgs>
      fields: Prisma.WorkPeriodFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WorkPeriodFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WorkPeriodFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>
        }
        findFirst: {
          args: Prisma.WorkPeriodFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WorkPeriodFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>
        }
        findMany: {
          args: Prisma.WorkPeriodFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>[]
        }
        create: {
          args: Prisma.WorkPeriodCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>
        }
        createMany: {
          args: Prisma.WorkPeriodCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WorkPeriodCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>[]
        }
        delete: {
          args: Prisma.WorkPeriodDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>
        }
        update: {
          args: Prisma.WorkPeriodUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>
        }
        deleteMany: {
          args: Prisma.WorkPeriodDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WorkPeriodUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WorkPeriodUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>[]
        }
        upsert: {
          args: Prisma.WorkPeriodUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkPeriodPayload>
        }
        aggregate: {
          args: Prisma.WorkPeriodAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorkPeriod>
        }
        groupBy: {
          args: Prisma.WorkPeriodGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorkPeriodGroupByOutputType>[]
        }
        count: {
          args: Prisma.WorkPeriodCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorkPeriodCountAggregateOutputType> | number
        }
      }
    }
    Video: {
      payload: Prisma.$VideoPayload<ExtArgs>
      fields: Prisma.VideoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VideoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VideoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>
        }
        findFirst: {
          args: Prisma.VideoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VideoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>
        }
        findMany: {
          args: Prisma.VideoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>[]
        }
        create: {
          args: Prisma.VideoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>
        }
        createMany: {
          args: Prisma.VideoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VideoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>[]
        }
        delete: {
          args: Prisma.VideoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>
        }
        update: {
          args: Prisma.VideoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>
        }
        deleteMany: {
          args: Prisma.VideoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VideoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VideoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>[]
        }
        upsert: {
          args: Prisma.VideoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VideoPayload>
        }
        aggregate: {
          args: Prisma.VideoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVideo>
        }
        groupBy: {
          args: Prisma.VideoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoGroupByOutputType>[]
        }
        count: {
          args: Prisma.VideoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VideoCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  phone: 'phone',
  description: 'description'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AdvertScalarFieldEnum = {
  id: 'id',
  advertId: 'advertId',
  firstName: 'firstName',
  lastName: 'lastName',
  fathersName: 'fathersName',
  gender: 'gender',
  category: 'category',
  subCategory: 'subCategory',
  title: 'title',
  profession: 'profession',
  sphere: 'sphere',
  brand: 'brand',
  model: 'model',
  yearOfmanufacture: 'yearOfmanufacture',
  color: 'color',
  isOnTheGo: 'isOnTheGo',
  vehicleBodyType: 'vehicleBodyType',
  vehicleKpp: 'vehicleKpp',
  ownersPts: 'ownersPts',
  milage: 'milage',
  engineCapacity: 'engineCapacity',
  horsePower: 'horsePower',
  drive: 'drive',
  steerinWheel: 'steerinWheel',
  price: 'price',
  priceFor: 'priceFor',
  vesselType: 'vesselType',
  vesselLength: 'vesselLength',
  vesselWidth: 'vesselWidth',
  vesselDraft: 'vesselDraft',
  maxPassengers: 'maxPassengers',
  vesselBodyMaterial: 'vesselBodyMaterial',
  engineType: 'engineType',
  cooling: 'cooling',
  propertyType: 'propertyType',
  totalArea: 'totalArea',
  livingArea: 'livingArea',
  kitchenArea: 'kitchenArea',
  apartmentFloor: 'apartmentFloor',
  floorsInHouse: 'floorsInHouse',
  houseState: 'houseState',
  hasBalcony: 'hasBalcony',
  balconyAmount: 'balconyAmount',
  hasElevator: 'hasElevator',
  hasParking: 'hasParking',
  stationDistance: 'stationDistance',
  cityInfrastructure: 'cityInfrastructure',
  cityInfrastructureDistance: 'cityInfrastructureDistance',
  hasSecurity: 'hasSecurity',
  hasVideoSecurity: 'hasVideoSecurity',
  hasChildrenPlayground: 'hasChildrenPlayground',
  hasSportPlayground: 'hasSportPlayground',
  paymentType: 'paymentType',
  hasDocuments: 'hasDocuments',
  description: 'description',
  workExperience: 'workExperience',
  advanteges: 'advanteges',
  employment: 'employment',
  workFormat: 'workFormat',
  petBreed: 'petBreed',
  petName: 'petName',
  petColor: 'petColor',
  transactionScope: 'transactionScope',
  isProfitable: 'isProfitable',
  businessForm: 'businessForm',
  offerType: 'offerType',
  payBackPeriod: 'payBackPeriod',
  address: 'address',
  contacts: 'contacts',
  userId: 'userId',
  videoId: 'videoId'
} as const

export type AdvertScalarFieldEnum = (typeof AdvertScalarFieldEnum)[keyof typeof AdvertScalarFieldEnum]


export const PicturesScalarFieldEnum = {
  id: 'id',
  pictureUrl: 'pictureUrl',
  advertId: 'advertId'
} as const

export type PicturesScalarFieldEnum = (typeof PicturesScalarFieldEnum)[keyof typeof PicturesScalarFieldEnum]


export const ServicesScalarFieldEnum = {
  id: 'id',
  text: 'text',
  advertId: 'advertId'
} as const

export type ServicesScalarFieldEnum = (typeof ServicesScalarFieldEnum)[keyof typeof ServicesScalarFieldEnum]


export const WorkPeriodScalarFieldEnum = {
  id: 'id',
  fromDay: 'fromDay',
  toDay: 'toDay',
  fromTime: 'fromTime',
  toTime: 'toTime',
  is24h: 'is24h',
  advertId: 'advertId'
} as const

export type WorkPeriodScalarFieldEnum = (typeof WorkPeriodScalarFieldEnum)[keyof typeof WorkPeriodScalarFieldEnum]


export const VideoScalarFieldEnum = {
  id: 'id',
  videoUrl: 'videoUrl',
  advertId: 'advertId'
} as const

export type VideoScalarFieldEnum = (typeof VideoScalarFieldEnum)[keyof typeof VideoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'VehicleKpp'
 */
export type EnumVehicleKppFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VehicleKpp'>
    


/**
 * Reference to a field of type 'VehicleKpp[]'
 */
export type ListEnumVehicleKppFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VehicleKpp[]'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'BigInt[]'
 */
export type ListBigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt[]'>
    


/**
 * Reference to a field of type 'Drive'
 */
export type EnumDriveFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Drive'>
    


/**
 * Reference to a field of type 'Drive[]'
 */
export type ListEnumDriveFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Drive[]'>
    


/**
 * Reference to a field of type 'SteeringWheel'
 */
export type EnumSteeringWheelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SteeringWheel'>
    


/**
 * Reference to a field of type 'SteeringWheel[]'
 */
export type ListEnumSteeringWheelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SteeringWheel[]'>
    


/**
 * Reference to a field of type 'PriceFor'
 */
export type EnumPriceForFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PriceFor'>
    


/**
 * Reference to a field of type 'PriceFor[]'
 */
export type ListEnumPriceForFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PriceFor[]'>
    


/**
 * Reference to a field of type 'VesselType'
 */
export type EnumVesselTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VesselType'>
    


/**
 * Reference to a field of type 'VesselType[]'
 */
export type ListEnumVesselTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VesselType[]'>
    


/**
 * Reference to a field of type 'Cooling'
 */
export type EnumCoolingFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Cooling'>
    


/**
 * Reference to a field of type 'Cooling[]'
 */
export type ListEnumCoolingFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Cooling[]'>
    


/**
 * Reference to a field of type 'PropertyType'
 */
export type EnumPropertyTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PropertyType'>
    


/**
 * Reference to a field of type 'PropertyType[]'
 */
export type ListEnumPropertyTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PropertyType[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'HouseState'
 */
export type EnumHouseStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HouseState'>
    


/**
 * Reference to a field of type 'HouseState[]'
 */
export type ListEnumHouseStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HouseState[]'>
    


/**
 * Reference to a field of type 'PaymentType'
 */
export type EnumPaymentTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PaymentType'>
    


/**
 * Reference to a field of type 'PaymentType[]'
 */
export type ListEnumPaymentTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PaymentType[]'>
    


/**
 * Reference to a field of type 'Employment'
 */
export type EnumEmploymentFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Employment'>
    


/**
 * Reference to a field of type 'Employment[]'
 */
export type ListEnumEmploymentFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Employment[]'>
    


/**
 * Reference to a field of type 'WorkFormat'
 */
export type EnumWorkFormatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorkFormat'>
    


/**
 * Reference to a field of type 'WorkFormat[]'
 */
export type ListEnumWorkFormatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorkFormat[]'>
    


/**
 * Reference to a field of type 'TransactionScope'
 */
export type EnumTransactionScopeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TransactionScope'>
    


/**
 * Reference to a field of type 'TransactionScope[]'
 */
export type ListEnumTransactionScopeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TransactionScope[]'>
    


/**
 * Reference to a field of type 'BusinessForm'
 */
export type EnumBusinessFormFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BusinessForm'>
    


/**
 * Reference to a field of type 'BusinessForm[]'
 */
export type ListEnumBusinessFormFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BusinessForm[]'>
    


/**
 * Reference to a field of type 'OfferType'
 */
export type EnumOfferTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OfferType'>
    


/**
 * Reference to a field of type 'OfferType[]'
 */
export type ListEnumOfferTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OfferType[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  advert?: Prisma.AdvertOmit
  pictures?: Prisma.PicturesOmit
  services?: Prisma.ServicesOmit
  workPeriod?: Prisma.WorkPeriodOmit
  video?: Prisma.VideoOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

