
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Advert: 'Advert',
  Pictures: 'Pictures',
  Services: 'Services',
  WorkPeriod: 'WorkPeriod',
  Video: 'Video'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  phone: 'phone',
  description: 'description'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AdvertScalarFieldEnum = {
  id: 'id',
  advertId: 'advertId',
  firstName: 'firstName',
  lastName: 'lastName',
  fathersName: 'fathersName',
  gender: 'gender',
  category: 'category',
  subCategory: 'subCategory',
  title: 'title',
  profession: 'profession',
  sphere: 'sphere',
  brand: 'brand',
  model: 'model',
  yearOfmanufacture: 'yearOfmanufacture',
  color: 'color',
  isOnTheGo: 'isOnTheGo',
  vehicleBodyType: 'vehicleBodyType',
  vehicleKpp: 'vehicleKpp',
  ownersPts: 'ownersPts',
  milage: 'milage',
  engineCapacity: 'engineCapacity',
  horsePower: 'horsePower',
  drive: 'drive',
  steerinWheel: 'steerinWheel',
  price: 'price',
  priceFor: 'priceFor',
  vesselType: 'vesselType',
  vesselLength: 'vesselLength',
  vesselWidth: 'vesselWidth',
  vesselDraft: 'vesselDraft',
  maxPassengers: 'maxPassengers',
  vesselBodyMaterial: 'vesselBodyMaterial',
  engineType: 'engineType',
  cooling: 'cooling',
  propertyType: 'propertyType',
  totalArea: 'totalArea',
  livingArea: 'livingArea',
  kitchenArea: 'kitchenArea',
  apartmentFloor: 'apartmentFloor',
  floorsInHouse: 'floorsInHouse',
  houseState: 'houseState',
  hasBalcony: 'hasBalcony',
  balconyAmount: 'balconyAmount',
  hasElevator: 'hasElevator',
  hasParking: 'hasParking',
  stationDistance: 'stationDistance',
  cityInfrastructure: 'cityInfrastructure',
  cityInfrastructureDistance: 'cityInfrastructureDistance',
  hasSecurity: 'hasSecurity',
  hasVideoSecurity: 'hasVideoSecurity',
  hasChildrenPlayground: 'hasChildrenPlayground',
  hasSportPlayground: 'hasSportPlayground',
  paymentType: 'paymentType',
  hasDocuments: 'hasDocuments',
  description: 'description',
  workExperience: 'workExperience',
  advanteges: 'advanteges',
  employment: 'employment',
  workFormat: 'workFormat',
  petBreed: 'petBreed',
  petName: 'petName',
  petColor: 'petColor',
  transactionScope: 'transactionScope',
  isProfitable: 'isProfitable',
  businessForm: 'businessForm',
  offerType: 'offerType',
  payBackPeriod: 'payBackPeriod',
  address: 'address',
  contacts: 'contacts',
  userId: 'userId',
  videoId: 'videoId'
} as const

export type AdvertScalarFieldEnum = (typeof AdvertScalarFieldEnum)[keyof typeof AdvertScalarFieldEnum]


export const PicturesScalarFieldEnum = {
  id: 'id',
  pictureUrl: 'pictureUrl',
  advertId: 'advertId'
} as const

export type PicturesScalarFieldEnum = (typeof PicturesScalarFieldEnum)[keyof typeof PicturesScalarFieldEnum]


export const ServicesScalarFieldEnum = {
  id: 'id',
  text: 'text',
  advertId: 'advertId'
} as const

export type ServicesScalarFieldEnum = (typeof ServicesScalarFieldEnum)[keyof typeof ServicesScalarFieldEnum]


export const WorkPeriodScalarFieldEnum = {
  id: 'id',
  fromDay: 'fromDay',
  toDay: 'toDay',
  fromTime: 'fromTime',
  toTime: 'toTime',
  is24h: 'is24h',
  advertId: 'advertId'
} as const

export type WorkPeriodScalarFieldEnum = (typeof WorkPeriodScalarFieldEnum)[keyof typeof WorkPeriodScalarFieldEnum]


export const VideoScalarFieldEnum = {
  id: 'id',
  videoUrl: 'videoUrl',
  advertId: 'advertId'
} as const

export type VideoScalarFieldEnum = (typeof VideoScalarFieldEnum)[keyof typeof VideoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

