
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkPeriod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorkPeriod
 * 
 */
export type WorkPeriodModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkPeriodPayload>

export type AggregateWorkPeriod = {
  _count: WorkPeriodCountAggregateOutputType | null
  _avg: WorkPeriodAvgAggregateOutputType | null
  _sum: WorkPeriodSumAggregateOutputType | null
  _min: WorkPeriodMinAggregateOutputType | null
  _max: WorkPeriodMaxAggregateOutputType | null
}

export type WorkPeriodAvgAggregateOutputType = {
  fromDay: number | null
  toDay: number | null
}

export type WorkPeriodSumAggregateOutputType = {
  fromDay: number | null
  toDay: number | null
}

export type WorkPeriodMinAggregateOutputType = {
  id: string | null
  fromDay: number | null
  toDay: number | null
  fromTime: string | null
  toTime: string | null
  is24h: boolean | null
  advertId: string | null
}

export type WorkPeriodMaxAggregateOutputType = {
  id: string | null
  fromDay: number | null
  toDay: number | null
  fromTime: string | null
  toTime: string | null
  is24h: boolean | null
  advertId: string | null
}

export type WorkPeriodCountAggregateOutputType = {
  id: number
  fromDay: number
  toDay: number
  fromTime: number
  toTime: number
  is24h: number
  advertId: number
  _all: number
}


export type WorkPeriodAvgAggregateInputType = {
  fromDay?: true
  toDay?: true
}

export type WorkPeriodSumAggregateInputType = {
  fromDay?: true
  toDay?: true
}

export type WorkPeriodMinAggregateInputType = {
  id?: true
  fromDay?: true
  toDay?: true
  fromTime?: true
  toTime?: true
  is24h?: true
  advertId?: true
}

export type WorkPeriodMaxAggregateInputType = {
  id?: true
  fromDay?: true
  toDay?: true
  fromTime?: true
  toTime?: true
  is24h?: true
  advertId?: true
}

export type WorkPeriodCountAggregateInputType = {
  id?: true
  fromDay?: true
  toDay?: true
  fromTime?: true
  toTime?: true
  is24h?: true
  advertId?: true
  _all?: true
}

export type WorkPeriodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkPeriod to aggregate.
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkPeriods to fetch.
   */
  orderBy?: Prisma.WorkPeriodOrderByWithRelationInput | Prisma.WorkPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkPeriods
  **/
  _count?: true | WorkPeriodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkPeriodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkPeriodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkPeriodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkPeriodMaxAggregateInputType
}

export type GetWorkPeriodAggregateType<T extends WorkPeriodAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkPeriod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkPeriod[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkPeriod[P]>
}




export type WorkPeriodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkPeriodWhereInput
  orderBy?: Prisma.WorkPeriodOrderByWithAggregationInput | Prisma.WorkPeriodOrderByWithAggregationInput[]
  by: Prisma.WorkPeriodScalarFieldEnum[] | Prisma.WorkPeriodScalarFieldEnum
  having?: Prisma.WorkPeriodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkPeriodCountAggregateInputType | true
  _avg?: WorkPeriodAvgAggregateInputType
  _sum?: WorkPeriodSumAggregateInputType
  _min?: WorkPeriodMinAggregateInputType
  _max?: WorkPeriodMaxAggregateInputType
}

export type WorkPeriodGroupByOutputType = {
  id: string
  fromDay: number
  toDay: number
  fromTime: string | null
  toTime: string | null
  is24h: boolean
  advertId: string
  _count: WorkPeriodCountAggregateOutputType | null
  _avg: WorkPeriodAvgAggregateOutputType | null
  _sum: WorkPeriodSumAggregateOutputType | null
  _min: WorkPeriodMinAggregateOutputType | null
  _max: WorkPeriodMaxAggregateOutputType | null
}

type GetWorkPeriodGroupByPayload<T extends WorkPeriodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkPeriodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkPeriodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkPeriodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkPeriodGroupByOutputType[P]>
      }
    >
  >



export type WorkPeriodWhereInput = {
  AND?: Prisma.WorkPeriodWhereInput | Prisma.WorkPeriodWhereInput[]
  OR?: Prisma.WorkPeriodWhereInput[]
  NOT?: Prisma.WorkPeriodWhereInput | Prisma.WorkPeriodWhereInput[]
  id?: Prisma.StringFilter<"WorkPeriod"> | string
  fromDay?: Prisma.IntFilter<"WorkPeriod"> | number
  toDay?: Prisma.IntFilter<"WorkPeriod"> | number
  fromTime?: Prisma.StringNullableFilter<"WorkPeriod"> | string | null
  toTime?: Prisma.StringNullableFilter<"WorkPeriod"> | string | null
  is24h?: Prisma.BoolFilter<"WorkPeriod"> | boolean
  advertId?: Prisma.StringFilter<"WorkPeriod"> | string
  advert?: Prisma.XOR<Prisma.AdvertScalarRelationFilter, Prisma.AdvertWhereInput>
}

export type WorkPeriodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
  fromTime?: Prisma.SortOrderInput | Prisma.SortOrder
  toTime?: Prisma.SortOrderInput | Prisma.SortOrder
  is24h?: Prisma.SortOrder
  advertId?: Prisma.SortOrder
  advert?: Prisma.AdvertOrderByWithRelationInput
}

export type WorkPeriodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkPeriodWhereInput | Prisma.WorkPeriodWhereInput[]
  OR?: Prisma.WorkPeriodWhereInput[]
  NOT?: Prisma.WorkPeriodWhereInput | Prisma.WorkPeriodWhereInput[]
  fromDay?: Prisma.IntFilter<"WorkPeriod"> | number
  toDay?: Prisma.IntFilter<"WorkPeriod"> | number
  fromTime?: Prisma.StringNullableFilter<"WorkPeriod"> | string | null
  toTime?: Prisma.StringNullableFilter<"WorkPeriod"> | string | null
  is24h?: Prisma.BoolFilter<"WorkPeriod"> | boolean
  advertId?: Prisma.StringFilter<"WorkPeriod"> | string
  advert?: Prisma.XOR<Prisma.AdvertScalarRelationFilter, Prisma.AdvertWhereInput>
}, "id">

export type WorkPeriodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
  fromTime?: Prisma.SortOrderInput | Prisma.SortOrder
  toTime?: Prisma.SortOrderInput | Prisma.SortOrder
  is24h?: Prisma.SortOrder
  advertId?: Prisma.SortOrder
  _count?: Prisma.WorkPeriodCountOrderByAggregateInput
  _avg?: Prisma.WorkPeriodAvgOrderByAggregateInput
  _max?: Prisma.WorkPeriodMaxOrderByAggregateInput
  _min?: Prisma.WorkPeriodMinOrderByAggregateInput
  _sum?: Prisma.WorkPeriodSumOrderByAggregateInput
}

export type WorkPeriodScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkPeriodScalarWhereWithAggregatesInput | Prisma.WorkPeriodScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkPeriodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkPeriodScalarWhereWithAggregatesInput | Prisma.WorkPeriodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkPeriod"> | string
  fromDay?: Prisma.IntWithAggregatesFilter<"WorkPeriod"> | number
  toDay?: Prisma.IntWithAggregatesFilter<"WorkPeriod"> | number
  fromTime?: Prisma.StringNullableWithAggregatesFilter<"WorkPeriod"> | string | null
  toTime?: Prisma.StringNullableWithAggregatesFilter<"WorkPeriod"> | string | null
  is24h?: Prisma.BoolWithAggregatesFilter<"WorkPeriod"> | boolean
  advertId?: Prisma.StringWithAggregatesFilter<"WorkPeriod"> | string
}

export type WorkPeriodCreateInput = {
  id?: string
  fromDay: number
  toDay: number
  fromTime?: string | null
  toTime?: string | null
  is24h?: boolean
  advert: Prisma.AdvertCreateNestedOneWithoutWorkScheduleInput
}

export type WorkPeriodUncheckedCreateInput = {
  id?: string
  fromDay: number
  toDay: number
  fromTime?: string | null
  toTime?: string | null
  is24h?: boolean
  advertId: string
}

export type WorkPeriodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
  advert?: Prisma.AdvertUpdateOneRequiredWithoutWorkScheduleNestedInput
}

export type WorkPeriodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
  advertId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkPeriodCreateManyInput = {
  id?: string
  fromDay: number
  toDay: number
  fromTime?: string | null
  toTime?: string | null
  is24h?: boolean
  advertId: string
}

export type WorkPeriodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type WorkPeriodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
  advertId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkPeriodListRelationFilter = {
  every?: Prisma.WorkPeriodWhereInput
  some?: Prisma.WorkPeriodWhereInput
  none?: Prisma.WorkPeriodWhereInput
}

export type WorkPeriodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkPeriodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
  fromTime?: Prisma.SortOrder
  toTime?: Prisma.SortOrder
  is24h?: Prisma.SortOrder
  advertId?: Prisma.SortOrder
}

export type WorkPeriodAvgOrderByAggregateInput = {
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
}

export type WorkPeriodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
  fromTime?: Prisma.SortOrder
  toTime?: Prisma.SortOrder
  is24h?: Prisma.SortOrder
  advertId?: Prisma.SortOrder
}

export type WorkPeriodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
  fromTime?: Prisma.SortOrder
  toTime?: Prisma.SortOrder
  is24h?: Prisma.SortOrder
  advertId?: Prisma.SortOrder
}

export type WorkPeriodSumOrderByAggregateInput = {
  fromDay?: Prisma.SortOrder
  toDay?: Prisma.SortOrder
}

export type WorkPeriodCreateNestedManyWithoutAdvertInput = {
  create?: Prisma.XOR<Prisma.WorkPeriodCreateWithoutAdvertInput, Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput> | Prisma.WorkPeriodCreateWithoutAdvertInput[] | Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput[]
  connectOrCreate?: Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput | Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput[]
  createMany?: Prisma.WorkPeriodCreateManyAdvertInputEnvelope
  connect?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
}

export type WorkPeriodUncheckedCreateNestedManyWithoutAdvertInput = {
  create?: Prisma.XOR<Prisma.WorkPeriodCreateWithoutAdvertInput, Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput> | Prisma.WorkPeriodCreateWithoutAdvertInput[] | Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput[]
  connectOrCreate?: Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput | Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput[]
  createMany?: Prisma.WorkPeriodCreateManyAdvertInputEnvelope
  connect?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
}

export type WorkPeriodUpdateManyWithoutAdvertNestedInput = {
  create?: Prisma.XOR<Prisma.WorkPeriodCreateWithoutAdvertInput, Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput> | Prisma.WorkPeriodCreateWithoutAdvertInput[] | Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput[]
  connectOrCreate?: Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput | Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput[]
  upsert?: Prisma.WorkPeriodUpsertWithWhereUniqueWithoutAdvertInput | Prisma.WorkPeriodUpsertWithWhereUniqueWithoutAdvertInput[]
  createMany?: Prisma.WorkPeriodCreateManyAdvertInputEnvelope
  set?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  disconnect?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  delete?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  connect?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  update?: Prisma.WorkPeriodUpdateWithWhereUniqueWithoutAdvertInput | Prisma.WorkPeriodUpdateWithWhereUniqueWithoutAdvertInput[]
  updateMany?: Prisma.WorkPeriodUpdateManyWithWhereWithoutAdvertInput | Prisma.WorkPeriodUpdateManyWithWhereWithoutAdvertInput[]
  deleteMany?: Prisma.WorkPeriodScalarWhereInput | Prisma.WorkPeriodScalarWhereInput[]
}

export type WorkPeriodUncheckedUpdateManyWithoutAdvertNestedInput = {
  create?: Prisma.XOR<Prisma.WorkPeriodCreateWithoutAdvertInput, Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput> | Prisma.WorkPeriodCreateWithoutAdvertInput[] | Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput[]
  connectOrCreate?: Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput | Prisma.WorkPeriodCreateOrConnectWithoutAdvertInput[]
  upsert?: Prisma.WorkPeriodUpsertWithWhereUniqueWithoutAdvertInput | Prisma.WorkPeriodUpsertWithWhereUniqueWithoutAdvertInput[]
  createMany?: Prisma.WorkPeriodCreateManyAdvertInputEnvelope
  set?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  disconnect?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  delete?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  connect?: Prisma.WorkPeriodWhereUniqueInput | Prisma.WorkPeriodWhereUniqueInput[]
  update?: Prisma.WorkPeriodUpdateWithWhereUniqueWithoutAdvertInput | Prisma.WorkPeriodUpdateWithWhereUniqueWithoutAdvertInput[]
  updateMany?: Prisma.WorkPeriodUpdateManyWithWhereWithoutAdvertInput | Prisma.WorkPeriodUpdateManyWithWhereWithoutAdvertInput[]
  deleteMany?: Prisma.WorkPeriodScalarWhereInput | Prisma.WorkPeriodScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type WorkPeriodCreateWithoutAdvertInput = {
  id?: string
  fromDay: number
  toDay: number
  fromTime?: string | null
  toTime?: string | null
  is24h?: boolean
}

export type WorkPeriodUncheckedCreateWithoutAdvertInput = {
  id?: string
  fromDay: number
  toDay: number
  fromTime?: string | null
  toTime?: string | null
  is24h?: boolean
}

export type WorkPeriodCreateOrConnectWithoutAdvertInput = {
  where: Prisma.WorkPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkPeriodCreateWithoutAdvertInput, Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput>
}

export type WorkPeriodCreateManyAdvertInputEnvelope = {
  data: Prisma.WorkPeriodCreateManyAdvertInput | Prisma.WorkPeriodCreateManyAdvertInput[]
  skipDuplicates?: boolean
}

export type WorkPeriodUpsertWithWhereUniqueWithoutAdvertInput = {
  where: Prisma.WorkPeriodWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkPeriodUpdateWithoutAdvertInput, Prisma.WorkPeriodUncheckedUpdateWithoutAdvertInput>
  create: Prisma.XOR<Prisma.WorkPeriodCreateWithoutAdvertInput, Prisma.WorkPeriodUncheckedCreateWithoutAdvertInput>
}

export type WorkPeriodUpdateWithWhereUniqueWithoutAdvertInput = {
  where: Prisma.WorkPeriodWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkPeriodUpdateWithoutAdvertInput, Prisma.WorkPeriodUncheckedUpdateWithoutAdvertInput>
}

export type WorkPeriodUpdateManyWithWhereWithoutAdvertInput = {
  where: Prisma.WorkPeriodScalarWhereInput
  data: Prisma.XOR<Prisma.WorkPeriodUpdateManyMutationInput, Prisma.WorkPeriodUncheckedUpdateManyWithoutAdvertInput>
}

export type WorkPeriodScalarWhereInput = {
  AND?: Prisma.WorkPeriodScalarWhereInput | Prisma.WorkPeriodScalarWhereInput[]
  OR?: Prisma.WorkPeriodScalarWhereInput[]
  NOT?: Prisma.WorkPeriodScalarWhereInput | Prisma.WorkPeriodScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkPeriod"> | string
  fromDay?: Prisma.IntFilter<"WorkPeriod"> | number
  toDay?: Prisma.IntFilter<"WorkPeriod"> | number
  fromTime?: Prisma.StringNullableFilter<"WorkPeriod"> | string | null
  toTime?: Prisma.StringNullableFilter<"WorkPeriod"> | string | null
  is24h?: Prisma.BoolFilter<"WorkPeriod"> | boolean
  advertId?: Prisma.StringFilter<"WorkPeriod"> | string
}

export type WorkPeriodCreateManyAdvertInput = {
  id?: string
  fromDay: number
  toDay: number
  fromTime?: string | null
  toTime?: string | null
  is24h?: boolean
}

export type WorkPeriodUpdateWithoutAdvertInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type WorkPeriodUncheckedUpdateWithoutAdvertInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type WorkPeriodUncheckedUpdateManyWithoutAdvertInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromDay?: Prisma.IntFieldUpdateOperationsInput | number
  toDay?: Prisma.IntFieldUpdateOperationsInput | number
  fromTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  toTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is24h?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type WorkPeriodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromDay?: boolean
  toDay?: boolean
  fromTime?: boolean
  toTime?: boolean
  is24h?: boolean
  advertId?: boolean
  advert?: boolean | Prisma.AdvertDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workPeriod"]>

export type WorkPeriodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromDay?: boolean
  toDay?: boolean
  fromTime?: boolean
  toTime?: boolean
  is24h?: boolean
  advertId?: boolean
  advert?: boolean | Prisma.AdvertDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workPeriod"]>

export type WorkPeriodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromDay?: boolean
  toDay?: boolean
  fromTime?: boolean
  toTime?: boolean
  is24h?: boolean
  advertId?: boolean
  advert?: boolean | Prisma.AdvertDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workPeriod"]>

export type WorkPeriodSelectScalar = {
  id?: boolean
  fromDay?: boolean
  toDay?: boolean
  fromTime?: boolean
  toTime?: boolean
  is24h?: boolean
  advertId?: boolean
}

export type WorkPeriodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fromDay" | "toDay" | "fromTime" | "toTime" | "is24h" | "advertId", ExtArgs["result"]["workPeriod"]>
export type WorkPeriodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  advert?: boolean | Prisma.AdvertDefaultArgs<ExtArgs>
}
export type WorkPeriodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  advert?: boolean | Prisma.AdvertDefaultArgs<ExtArgs>
}
export type WorkPeriodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  advert?: boolean | Prisma.AdvertDefaultArgs<ExtArgs>
}

export type $WorkPeriodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkPeriod"
  objects: {
    advert: Prisma.$AdvertPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fromDay: number
    toDay: number
    fromTime: string | null
    toTime: string | null
    is24h: boolean
    advertId: string
  }, ExtArgs["result"]["workPeriod"]>
  composites: {}
}

export type WorkPeriodGetPayload<S extends boolean | null | undefined | WorkPeriodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload, S>

export type WorkPeriodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkPeriodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkPeriodCountAggregateInputType | true
  }

export interface WorkPeriodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkPeriod'], meta: { name: 'WorkPeriod' } }
  /**
   * Find zero or one WorkPeriod that matches the filter.
   * @param {WorkPeriodFindUniqueArgs} args - Arguments to find a WorkPeriod
   * @example
   * // Get one WorkPeriod
   * const workPeriod = await prisma.workPeriod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkPeriodFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkPeriodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkPeriod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkPeriodFindUniqueOrThrowArgs} args - Arguments to find a WorkPeriod
   * @example
   * // Get one WorkPeriod
   * const workPeriod = await prisma.workPeriod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkPeriodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkPeriodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkPeriod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodFindFirstArgs} args - Arguments to find a WorkPeriod
   * @example
   * // Get one WorkPeriod
   * const workPeriod = await prisma.workPeriod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkPeriodFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkPeriodFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkPeriod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodFindFirstOrThrowArgs} args - Arguments to find a WorkPeriod
   * @example
   * // Get one WorkPeriod
   * const workPeriod = await prisma.workPeriod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkPeriodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkPeriodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkPeriods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkPeriods
   * const workPeriods = await prisma.workPeriod.findMany()
   * 
   * // Get first 10 WorkPeriods
   * const workPeriods = await prisma.workPeriod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workPeriodWithIdOnly = await prisma.workPeriod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkPeriodFindManyArgs>(args?: Prisma.SelectSubset<T, WorkPeriodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkPeriod.
   * @param {WorkPeriodCreateArgs} args - Arguments to create a WorkPeriod.
   * @example
   * // Create one WorkPeriod
   * const WorkPeriod = await prisma.workPeriod.create({
   *   data: {
   *     // ... data to create a WorkPeriod
   *   }
   * })
   * 
   */
  create<T extends WorkPeriodCreateArgs>(args: Prisma.SelectSubset<T, WorkPeriodCreateArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkPeriods.
   * @param {WorkPeriodCreateManyArgs} args - Arguments to create many WorkPeriods.
   * @example
   * // Create many WorkPeriods
   * const workPeriod = await prisma.workPeriod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkPeriodCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkPeriodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkPeriods and returns the data saved in the database.
   * @param {WorkPeriodCreateManyAndReturnArgs} args - Arguments to create many WorkPeriods.
   * @example
   * // Create many WorkPeriods
   * const workPeriod = await prisma.workPeriod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkPeriods and only return the `id`
   * const workPeriodWithIdOnly = await prisma.workPeriod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkPeriodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkPeriodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkPeriod.
   * @param {WorkPeriodDeleteArgs} args - Arguments to delete one WorkPeriod.
   * @example
   * // Delete one WorkPeriod
   * const WorkPeriod = await prisma.workPeriod.delete({
   *   where: {
   *     // ... filter to delete one WorkPeriod
   *   }
   * })
   * 
   */
  delete<T extends WorkPeriodDeleteArgs>(args: Prisma.SelectSubset<T, WorkPeriodDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkPeriod.
   * @param {WorkPeriodUpdateArgs} args - Arguments to update one WorkPeriod.
   * @example
   * // Update one WorkPeriod
   * const workPeriod = await prisma.workPeriod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkPeriodUpdateArgs>(args: Prisma.SelectSubset<T, WorkPeriodUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkPeriods.
   * @param {WorkPeriodDeleteManyArgs} args - Arguments to filter WorkPeriods to delete.
   * @example
   * // Delete a few WorkPeriods
   * const { count } = await prisma.workPeriod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkPeriodDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkPeriodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkPeriods
   * const workPeriod = await prisma.workPeriod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkPeriodUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkPeriodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkPeriods and returns the data updated in the database.
   * @param {WorkPeriodUpdateManyAndReturnArgs} args - Arguments to update many WorkPeriods.
   * @example
   * // Update many WorkPeriods
   * const workPeriod = await prisma.workPeriod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkPeriods and only return the `id`
   * const workPeriodWithIdOnly = await prisma.workPeriod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkPeriodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkPeriodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkPeriod.
   * @param {WorkPeriodUpsertArgs} args - Arguments to update or create a WorkPeriod.
   * @example
   * // Update or create a WorkPeriod
   * const workPeriod = await prisma.workPeriod.upsert({
   *   create: {
   *     // ... data to create a WorkPeriod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkPeriod we want to update
   *   }
   * })
   */
  upsert<T extends WorkPeriodUpsertArgs>(args: Prisma.SelectSubset<T, WorkPeriodUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkPeriodClient<runtime.Types.Result.GetResult<Prisma.$WorkPeriodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodCountArgs} args - Arguments to filter WorkPeriods to count.
   * @example
   * // Count the number of WorkPeriods
   * const count = await prisma.workPeriod.count({
   *   where: {
   *     // ... the filter for the WorkPeriods we want to count
   *   }
   * })
  **/
  count<T extends WorkPeriodCountArgs>(
    args?: Prisma.Subset<T, WorkPeriodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkPeriodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkPeriodAggregateArgs>(args: Prisma.Subset<T, WorkPeriodAggregateArgs>): Prisma.PrismaPromise<GetWorkPeriodAggregateType<T>>

  /**
   * Group by WorkPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkPeriodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkPeriodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkPeriodGroupByArgs['orderBy'] }
      : { orderBy?: WorkPeriodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkPeriodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkPeriodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkPeriod model
 */
readonly fields: WorkPeriodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkPeriod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkPeriodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  advert<T extends Prisma.AdvertDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdvertDefaultArgs<ExtArgs>>): Prisma.Prisma__AdvertClient<runtime.Types.Result.GetResult<Prisma.$AdvertPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkPeriod model
 */
export interface WorkPeriodFieldRefs {
  readonly id: Prisma.FieldRef<"WorkPeriod", 'String'>
  readonly fromDay: Prisma.FieldRef<"WorkPeriod", 'Int'>
  readonly toDay: Prisma.FieldRef<"WorkPeriod", 'Int'>
  readonly fromTime: Prisma.FieldRef<"WorkPeriod", 'String'>
  readonly toTime: Prisma.FieldRef<"WorkPeriod", 'String'>
  readonly is24h: Prisma.FieldRef<"WorkPeriod", 'Boolean'>
  readonly advertId: Prisma.FieldRef<"WorkPeriod", 'String'>
}
    

// Custom InputTypes
/**
 * WorkPeriod findUnique
 */
export type WorkPeriodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * Filter, which WorkPeriod to fetch.
   */
  where: Prisma.WorkPeriodWhereUniqueInput
}

/**
 * WorkPeriod findUniqueOrThrow
 */
export type WorkPeriodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * Filter, which WorkPeriod to fetch.
   */
  where: Prisma.WorkPeriodWhereUniqueInput
}

/**
 * WorkPeriod findFirst
 */
export type WorkPeriodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * Filter, which WorkPeriod to fetch.
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkPeriods to fetch.
   */
  orderBy?: Prisma.WorkPeriodOrderByWithRelationInput | Prisma.WorkPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkPeriods.
   */
  cursor?: Prisma.WorkPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkPeriods.
   */
  distinct?: Prisma.WorkPeriodScalarFieldEnum | Prisma.WorkPeriodScalarFieldEnum[]
}

/**
 * WorkPeriod findFirstOrThrow
 */
export type WorkPeriodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * Filter, which WorkPeriod to fetch.
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkPeriods to fetch.
   */
  orderBy?: Prisma.WorkPeriodOrderByWithRelationInput | Prisma.WorkPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkPeriods.
   */
  cursor?: Prisma.WorkPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkPeriods.
   */
  distinct?: Prisma.WorkPeriodScalarFieldEnum | Prisma.WorkPeriodScalarFieldEnum[]
}

/**
 * WorkPeriod findMany
 */
export type WorkPeriodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * Filter, which WorkPeriods to fetch.
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkPeriods to fetch.
   */
  orderBy?: Prisma.WorkPeriodOrderByWithRelationInput | Prisma.WorkPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkPeriods.
   */
  cursor?: Prisma.WorkPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkPeriods.
   */
  skip?: number
  distinct?: Prisma.WorkPeriodScalarFieldEnum | Prisma.WorkPeriodScalarFieldEnum[]
}

/**
 * WorkPeriod create
 */
export type WorkPeriodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkPeriod.
   */
  data: Prisma.XOR<Prisma.WorkPeriodCreateInput, Prisma.WorkPeriodUncheckedCreateInput>
}

/**
 * WorkPeriod createMany
 */
export type WorkPeriodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkPeriods.
   */
  data: Prisma.WorkPeriodCreateManyInput | Prisma.WorkPeriodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkPeriod createManyAndReturn
 */
export type WorkPeriodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * The data used to create many WorkPeriods.
   */
  data: Prisma.WorkPeriodCreateManyInput | Prisma.WorkPeriodCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkPeriod update
 */
export type WorkPeriodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkPeriod.
   */
  data: Prisma.XOR<Prisma.WorkPeriodUpdateInput, Prisma.WorkPeriodUncheckedUpdateInput>
  /**
   * Choose, which WorkPeriod to update.
   */
  where: Prisma.WorkPeriodWhereUniqueInput
}

/**
 * WorkPeriod updateMany
 */
export type WorkPeriodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkPeriods.
   */
  data: Prisma.XOR<Prisma.WorkPeriodUpdateManyMutationInput, Prisma.WorkPeriodUncheckedUpdateManyInput>
  /**
   * Filter which WorkPeriods to update
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * Limit how many WorkPeriods to update.
   */
  limit?: number
}

/**
 * WorkPeriod updateManyAndReturn
 */
export type WorkPeriodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * The data used to update WorkPeriods.
   */
  data: Prisma.XOR<Prisma.WorkPeriodUpdateManyMutationInput, Prisma.WorkPeriodUncheckedUpdateManyInput>
  /**
   * Filter which WorkPeriods to update
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * Limit how many WorkPeriods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkPeriod upsert
 */
export type WorkPeriodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkPeriod to update in case it exists.
   */
  where: Prisma.WorkPeriodWhereUniqueInput
  /**
   * In case the WorkPeriod found by the `where` argument doesn't exist, create a new WorkPeriod with this data.
   */
  create: Prisma.XOR<Prisma.WorkPeriodCreateInput, Prisma.WorkPeriodUncheckedCreateInput>
  /**
   * In case the WorkPeriod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkPeriodUpdateInput, Prisma.WorkPeriodUncheckedUpdateInput>
}

/**
 * WorkPeriod delete
 */
export type WorkPeriodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
  /**
   * Filter which WorkPeriod to delete.
   */
  where: Prisma.WorkPeriodWhereUniqueInput
}

/**
 * WorkPeriod deleteMany
 */
export type WorkPeriodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkPeriods to delete
   */
  where?: Prisma.WorkPeriodWhereInput
  /**
   * Limit how many WorkPeriods to delete.
   */
  limit?: number
}

/**
 * WorkPeriod without action
 */
export type WorkPeriodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkPeriod
   */
  select?: Prisma.WorkPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkPeriod
   */
  omit?: Prisma.WorkPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkPeriodInclude<ExtArgs> | null
}
