CREATE TABLE adverts
(
    id                           UUID         NOT NULL PRIMARY KEY,
    first_name                   VARCHAR(255),
    last_name                    VARCHAR(255),
    fathers_name                 VARCHAR(255),
    gender                       VARCHAR(50),
    category                     VARCHAR(255) NOT NULL,
    sub_category                 VARCHAR(255),
    title                        VARCHAR(255) NOT NULL,
    profession                   VARCHAR(255),
    sphere                       VARCHAR(255),
    brand                        VARCHAR(255),
    model                        VARCHAR(255),
    year_of_manufacture          INT,
    color                        VARCHAR(100),
    is_on_the_go                 BOOLEAN,
    vehicle_body_type            VARCHAR(255),
    vehicle_kpp                  VARCHAR(50),
    owners_pts                   INT,
    milage                       BIGINT,
    engine_capacity              INT,
    horse_power                  INT,
    drive                        VARCHAR(50),
    steering_wheel               VARCHAR(50),
    price                        VARCHAR(255) NOT NULL,
    price_for                    VARCHAR(50),
    vessel_type                  VARCHAR(50),
    vessel_length                INT,
    vessel_width                 INT,
    vessel_draft                 INT,
    max_passengers               INT,
    vessel_body_material         VARCHAR(255),
    engine_type                  VARCHAR(255),
    cooling                      VARCHAR(50),
    property_type                VARCHAR(50),
    total_area                   NUMERIC(10, 2),
    living_area                  NUMERIC(10, 2),
    kitchen_area                 NUMERIC(10, 2),
    apartment_floor              INT,
    floors_in_house              INT,
    house_state                  VARCHAR(50),
    has_balcony                  BOOLEAN,
    balcony_amount               INT,
    has_elevator                 BOOLEAN,
    has_parking                  BOOLEAN,
    station_distance             INT,
    city_infrastructure          BOOLEAN,
    city_infrastructure_distance INT,
    has_security                 BOOLEAN,
    has_video_security           BOOLEAN,
    has_children_playground      BOOLEAN,
    has_sport_playground         BOOLEAN,
    payment_type                 VARCHAR(50),
    has_documents                BOOLEAN,
    description                  TEXT         NOT NULL,
    work_experience              NUMERIC(10, 2),
    advantages                   TEXT,
    employment                   VARCHAR(50),
    work_format                  VARCHAR(50),
    pet_breed                    VARCHAR(255),
    pet_name                     VARCHAR(255),
    pet_color                    VARCHAR(255),
    transaction_scope            VARCHAR(50),
    is_profitable                BOOLEAN,
    business_form                VARCHAR(50),
    offer_type                   VARCHAR(50),
    pay_back_period              VARCHAR(255),
    address                      VARCHAR(255) NOT NULL,
    contacts                     VARCHAR(255) NOT NULL,
    is_in_elastic                BOOLEAN      NOT NULL DEFAULT FALSE,
    user_id                      VARCHAR(255) NOT NULL,
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    updated_at                   TIMESTAMP WITHOUT TIME ZONE
);