CREATE TABLE IF NOT EXISTS adverts
(
    id                           VARCHAR(255) NOT NULL,
    advert_id                    VARCHAR(255),
    first_name                   VARCHAR(255),
    last_name                    VARCHAR(255),
    fathers_name                 VARCHAR(255),
    gender                       VARCHAR(255),
    category                     VARCHAR(255) NOT NULL,
    sub_category                 VARCHAR(255),
    title                        VARCHAR(255) NOT NULL,
    profession                   VARCHAR(255),
    sphere                       VARCHAR(255),
    brand                        VARCHAR(255),
    model                        VARCHAR(255),
    year_of_manufacture          INTEGER,
    color                        VARCHAR(255),
    is_on_the_go                 BOOLEAN,
    vehicle_body_type            VARCHAR(255),
    vehicle_kpp                  VARCHAR(255),
    owners_pts                   INTEGER,
    milage                       BIGINT,
    engine_capacity              INTEGER,
    horse_power                  INTEGER,
    drive                        VARCHAR(255),
    steering_wheel               VARCHAR(255),
    price                        VARCHAR(255) NOT NULL,
    price_for                    VARCHAR(255),
    vessel_type                  VARCHAR(255),
    vessel_length                INTEGER,
    vessel_width                 INTEGER,
    vessel_draft                 INTEGER,
    max_passengers               INTEGER,
    vessel_body_material         VARCHAR(255),
    engine_type                  VARCHAR(255),
    cooling                      VARCHAR(255),
    property_type                VARCHAR(255),
    total_area                   DECIMAL(10, 2),
    living_area                  DECIMAL(10, 2),
    kitchen_area                 DECIMAL(10, 2),
    apartment_floor              INTEGER,
    floors_in_house              INTEGER,
    house_state                  VARCHAR(255),
    has_balcony                  BOOLEAN,
    balcony_amount               INTEGER,
    has_elevator                 BOOLEAN,
    has_parking                  BOOLEAN,
    station_distance             INTEGER,
    city_infrastructure          BOOLEAN,
    city_infrastructure_distance INTEGER,
    has_security                 BOOLEAN,
    has_video_security           BOOLEAN,
    has_children_playground      BOOLEAN,
    has_sport_playground         BOOLEAN,
    payment_type                 VARCHAR(255),
    has_documents                BOOLEAN,
    description                  VARCHAR(255) NOT NULL,
    work_experience              DECIMAL(10, 2),
    advantages                   VARCHAR(255),
    employment                   VARCHAR(255),
    work_format                  VARCHAR(255),
    pet_breed                    VARCHAR(255),
    pet_name                     VARCHAR(255),
    pet_color                    VARCHAR(255),
    transaction_scope            VARCHAR(255),
    is_profitable                BOOLEAN,
    business_form                VARCHAR(255),
    offer_type                   VARCHAR(255),
    pay_back_period              VARCHAR(255),
    address                      VARCHAR(255) NOT NULL,
    contacts                     VARCHAR(255) NOT NULL,
    user_id                      VARCHAR(255) NOT NULL,
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    updated_at                   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_adverts PRIMARY KEY (id)
);