CREATE TABLE IF NOT EXISTS services
(
    id        VARCHAR(255) NOT NULL,
    text      VARCHAR(255) NOT NULL,
    advert_id VARCHAR(255) NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (id)
);

ALTER TABLE services
    ADD CONSTRAINT FK_SERVICES_ON_ADVERT FOREIGN KEY (advert_id) REFERENCES adverts (id);