
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type BoolNullableFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableFilter<$PrismaModel> | boolean | null
}

export type EnumVehicleKppNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.VehicleKpp | Prisma.EnumVehicleKppFieldRefInput<$PrismaModel> | null
  in?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVehicleKppNullableFilter<$PrismaModel> | $Enums.VehicleKpp | null
}

export type BigIntNullableFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableFilter<$PrismaModel> | bigint | number | null
}

export type EnumDriveNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Drive | Prisma.EnumDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDriveNullableFilter<$PrismaModel> | $Enums.Drive | null
}

export type EnumSteeringWheelNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.SteeringWheel | Prisma.EnumSteeringWheelFieldRefInput<$PrismaModel> | null
  in?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumSteeringWheelNullableFilter<$PrismaModel> | $Enums.SteeringWheel | null
}

export type EnumPriceForNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.PriceFor | Prisma.EnumPriceForFieldRefInput<$PrismaModel> | null
  in?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPriceForNullableFilter<$PrismaModel> | $Enums.PriceFor | null
}

export type EnumVesselTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.VesselType | Prisma.EnumVesselTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVesselTypeNullableFilter<$PrismaModel> | $Enums.VesselType | null
}

export type EnumCoolingNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Cooling | Prisma.EnumCoolingFieldRefInput<$PrismaModel> | null
  in?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCoolingNullableFilter<$PrismaModel> | $Enums.Cooling | null
}

export type EnumPropertyTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.PropertyType | Prisma.EnumPropertyTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPropertyTypeNullableFilter<$PrismaModel> | $Enums.PropertyType | null
}

export type DecimalNullableFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel> | null
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalNullableFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type EnumHouseStateNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.HouseState | Prisma.EnumHouseStateFieldRefInput<$PrismaModel> | null
  in?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumHouseStateNullableFilter<$PrismaModel> | $Enums.HouseState | null
}

export type EnumPaymentTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentType | Prisma.EnumPaymentTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPaymentTypeNullableFilter<$PrismaModel> | $Enums.PaymentType | null
}

export type EnumEmploymentNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Employment | Prisma.EnumEmploymentFieldRefInput<$PrismaModel> | null
  in?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumEmploymentNullableFilter<$PrismaModel> | $Enums.Employment | null
}

export type EnumWorkFormatNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkFormat | Prisma.EnumWorkFormatFieldRefInput<$PrismaModel> | null
  in?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumWorkFormatNullableFilter<$PrismaModel> | $Enums.WorkFormat | null
}

export type EnumTransactionScopeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionScope | Prisma.EnumTransactionScopeFieldRefInput<$PrismaModel> | null
  in?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumTransactionScopeNullableFilter<$PrismaModel> | $Enums.TransactionScope | null
}

export type EnumBusinessFormNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.BusinessForm | Prisma.EnumBusinessFormFieldRefInput<$PrismaModel> | null
  in?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumBusinessFormNullableFilter<$PrismaModel> | $Enums.BusinessForm | null
}

export type EnumOfferTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.OfferType | Prisma.EnumOfferTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumOfferTypeNullableFilter<$PrismaModel> | $Enums.OfferType | null
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type BoolNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableWithAggregatesFilter<$PrismaModel> | boolean | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBoolNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBoolNullableFilter<$PrismaModel>
}

export type EnumVehicleKppNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VehicleKpp | Prisma.EnumVehicleKppFieldRefInput<$PrismaModel> | null
  in?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVehicleKppNullableWithAggregatesFilter<$PrismaModel> | $Enums.VehicleKpp | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVehicleKppNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVehicleKppNullableFilter<$PrismaModel>
}

export type BigIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableWithAggregatesFilter<$PrismaModel> | bigint | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
}

export type EnumDriveNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Drive | Prisma.EnumDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDriveNullableWithAggregatesFilter<$PrismaModel> | $Enums.Drive | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDriveNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDriveNullableFilter<$PrismaModel>
}

export type EnumSteeringWheelNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SteeringWheel | Prisma.EnumSteeringWheelFieldRefInput<$PrismaModel> | null
  in?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumSteeringWheelNullableWithAggregatesFilter<$PrismaModel> | $Enums.SteeringWheel | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSteeringWheelNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSteeringWheelNullableFilter<$PrismaModel>
}

export type EnumPriceForNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PriceFor | Prisma.EnumPriceForFieldRefInput<$PrismaModel> | null
  in?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPriceForNullableWithAggregatesFilter<$PrismaModel> | $Enums.PriceFor | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPriceForNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPriceForNullableFilter<$PrismaModel>
}

export type EnumVesselTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VesselType | Prisma.EnumVesselTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVesselTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.VesselType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVesselTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVesselTypeNullableFilter<$PrismaModel>
}

export type EnumCoolingNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Cooling | Prisma.EnumCoolingFieldRefInput<$PrismaModel> | null
  in?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCoolingNullableWithAggregatesFilter<$PrismaModel> | $Enums.Cooling | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCoolingNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCoolingNullableFilter<$PrismaModel>
}

export type EnumPropertyTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PropertyType | Prisma.EnumPropertyTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPropertyTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.PropertyType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPropertyTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPropertyTypeNullableFilter<$PrismaModel>
}

export type DecimalNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel> | null
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalNullableWithAggregatesFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
}

export type EnumHouseStateNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HouseState | Prisma.EnumHouseStateFieldRefInput<$PrismaModel> | null
  in?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumHouseStateNullableWithAggregatesFilter<$PrismaModel> | $Enums.HouseState | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHouseStateNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHouseStateNullableFilter<$PrismaModel>
}

export type EnumPaymentTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentType | Prisma.EnumPaymentTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPaymentTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.PaymentType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPaymentTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPaymentTypeNullableFilter<$PrismaModel>
}

export type EnumEmploymentNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Employment | Prisma.EnumEmploymentFieldRefInput<$PrismaModel> | null
  in?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumEmploymentNullableWithAggregatesFilter<$PrismaModel> | $Enums.Employment | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmploymentNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmploymentNullableFilter<$PrismaModel>
}

export type EnumWorkFormatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkFormat | Prisma.EnumWorkFormatFieldRefInput<$PrismaModel> | null
  in?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumWorkFormatNullableWithAggregatesFilter<$PrismaModel> | $Enums.WorkFormat | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorkFormatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorkFormatNullableFilter<$PrismaModel>
}

export type EnumTransactionScopeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionScope | Prisma.EnumTransactionScopeFieldRefInput<$PrismaModel> | null
  in?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumTransactionScopeNullableWithAggregatesFilter<$PrismaModel> | $Enums.TransactionScope | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTransactionScopeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTransactionScopeNullableFilter<$PrismaModel>
}

export type EnumBusinessFormNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BusinessForm | Prisma.EnumBusinessFormFieldRefInput<$PrismaModel> | null
  in?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumBusinessFormNullableWithAggregatesFilter<$PrismaModel> | $Enums.BusinessForm | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBusinessFormNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBusinessFormNullableFilter<$PrismaModel>
}

export type EnumOfferTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.OfferType | Prisma.EnumOfferTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumOfferTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.OfferType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumOfferTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumOfferTypeNullableFilter<$PrismaModel>
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolNullableFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableFilter<$PrismaModel> | boolean | null
}

export type NestedEnumVehicleKppNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.VehicleKpp | Prisma.EnumVehicleKppFieldRefInput<$PrismaModel> | null
  in?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVehicleKppNullableFilter<$PrismaModel> | $Enums.VehicleKpp | null
}

export type NestedBigIntNullableFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableFilter<$PrismaModel> | bigint | number | null
}

export type NestedEnumDriveNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Drive | Prisma.EnumDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDriveNullableFilter<$PrismaModel> | $Enums.Drive | null
}

export type NestedEnumSteeringWheelNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.SteeringWheel | Prisma.EnumSteeringWheelFieldRefInput<$PrismaModel> | null
  in?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumSteeringWheelNullableFilter<$PrismaModel> | $Enums.SteeringWheel | null
}

export type NestedEnumPriceForNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.PriceFor | Prisma.EnumPriceForFieldRefInput<$PrismaModel> | null
  in?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPriceForNullableFilter<$PrismaModel> | $Enums.PriceFor | null
}

export type NestedEnumVesselTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.VesselType | Prisma.EnumVesselTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVesselTypeNullableFilter<$PrismaModel> | $Enums.VesselType | null
}

export type NestedEnumCoolingNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Cooling | Prisma.EnumCoolingFieldRefInput<$PrismaModel> | null
  in?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCoolingNullableFilter<$PrismaModel> | $Enums.Cooling | null
}

export type NestedEnumPropertyTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.PropertyType | Prisma.EnumPropertyTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPropertyTypeNullableFilter<$PrismaModel> | $Enums.PropertyType | null
}

export type NestedDecimalNullableFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel> | null
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalNullableFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type NestedEnumHouseStateNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.HouseState | Prisma.EnumHouseStateFieldRefInput<$PrismaModel> | null
  in?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumHouseStateNullableFilter<$PrismaModel> | $Enums.HouseState | null
}

export type NestedEnumPaymentTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentType | Prisma.EnumPaymentTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPaymentTypeNullableFilter<$PrismaModel> | $Enums.PaymentType | null
}

export type NestedEnumEmploymentNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Employment | Prisma.EnumEmploymentFieldRefInput<$PrismaModel> | null
  in?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumEmploymentNullableFilter<$PrismaModel> | $Enums.Employment | null
}

export type NestedEnumWorkFormatNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkFormat | Prisma.EnumWorkFormatFieldRefInput<$PrismaModel> | null
  in?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumWorkFormatNullableFilter<$PrismaModel> | $Enums.WorkFormat | null
}

export type NestedEnumTransactionScopeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionScope | Prisma.EnumTransactionScopeFieldRefInput<$PrismaModel> | null
  in?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumTransactionScopeNullableFilter<$PrismaModel> | $Enums.TransactionScope | null
}

export type NestedEnumBusinessFormNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.BusinessForm | Prisma.EnumBusinessFormFieldRefInput<$PrismaModel> | null
  in?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumBusinessFormNullableFilter<$PrismaModel> | $Enums.BusinessForm | null
}

export type NestedEnumOfferTypeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.OfferType | Prisma.EnumOfferTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumOfferTypeNullableFilter<$PrismaModel> | $Enums.OfferType | null
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableWithAggregatesFilter<$PrismaModel> | boolean | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBoolNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBoolNullableFilter<$PrismaModel>
}

export type NestedEnumVehicleKppNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VehicleKpp | Prisma.EnumVehicleKppFieldRefInput<$PrismaModel> | null
  in?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VehicleKpp[] | Prisma.ListEnumVehicleKppFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVehicleKppNullableWithAggregatesFilter<$PrismaModel> | $Enums.VehicleKpp | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVehicleKppNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVehicleKppNullableFilter<$PrismaModel>
}

export type NestedBigIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableWithAggregatesFilter<$PrismaModel> | bigint | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
}

export type NestedEnumDriveNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Drive | Prisma.EnumDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Drive[] | Prisma.ListEnumDriveFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDriveNullableWithAggregatesFilter<$PrismaModel> | $Enums.Drive | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDriveNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDriveNullableFilter<$PrismaModel>
}

export type NestedEnumSteeringWheelNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SteeringWheel | Prisma.EnumSteeringWheelFieldRefInput<$PrismaModel> | null
  in?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.SteeringWheel[] | Prisma.ListEnumSteeringWheelFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumSteeringWheelNullableWithAggregatesFilter<$PrismaModel> | $Enums.SteeringWheel | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSteeringWheelNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSteeringWheelNullableFilter<$PrismaModel>
}

export type NestedEnumPriceForNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PriceFor | Prisma.EnumPriceForFieldRefInput<$PrismaModel> | null
  in?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PriceFor[] | Prisma.ListEnumPriceForFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPriceForNullableWithAggregatesFilter<$PrismaModel> | $Enums.PriceFor | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPriceForNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPriceForNullableFilter<$PrismaModel>
}

export type NestedEnumVesselTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VesselType | Prisma.EnumVesselTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.VesselType[] | Prisma.ListEnumVesselTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumVesselTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.VesselType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVesselTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVesselTypeNullableFilter<$PrismaModel>
}

export type NestedEnumCoolingNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Cooling | Prisma.EnumCoolingFieldRefInput<$PrismaModel> | null
  in?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Cooling[] | Prisma.ListEnumCoolingFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCoolingNullableWithAggregatesFilter<$PrismaModel> | $Enums.Cooling | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCoolingNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCoolingNullableFilter<$PrismaModel>
}

export type NestedEnumPropertyTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PropertyType | Prisma.EnumPropertyTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PropertyType[] | Prisma.ListEnumPropertyTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPropertyTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.PropertyType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPropertyTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPropertyTypeNullableFilter<$PrismaModel>
}

export type NestedDecimalNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel> | null
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalNullableWithAggregatesFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDecimalNullableFilter<$PrismaModel>
}

export type NestedEnumHouseStateNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HouseState | Prisma.EnumHouseStateFieldRefInput<$PrismaModel> | null
  in?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.HouseState[] | Prisma.ListEnumHouseStateFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumHouseStateNullableWithAggregatesFilter<$PrismaModel> | $Enums.HouseState | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHouseStateNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHouseStateNullableFilter<$PrismaModel>
}

export type NestedEnumPaymentTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentType | Prisma.EnumPaymentTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.PaymentType[] | Prisma.ListEnumPaymentTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumPaymentTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.PaymentType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPaymentTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPaymentTypeNullableFilter<$PrismaModel>
}

export type NestedEnumEmploymentNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Employment | Prisma.EnumEmploymentFieldRefInput<$PrismaModel> | null
  in?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Employment[] | Prisma.ListEnumEmploymentFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumEmploymentNullableWithAggregatesFilter<$PrismaModel> | $Enums.Employment | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmploymentNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmploymentNullableFilter<$PrismaModel>
}

export type NestedEnumWorkFormatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkFormat | Prisma.EnumWorkFormatFieldRefInput<$PrismaModel> | null
  in?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.WorkFormat[] | Prisma.ListEnumWorkFormatFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumWorkFormatNullableWithAggregatesFilter<$PrismaModel> | $Enums.WorkFormat | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorkFormatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorkFormatNullableFilter<$PrismaModel>
}

export type NestedEnumTransactionScopeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionScope | Prisma.EnumTransactionScopeFieldRefInput<$PrismaModel> | null
  in?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TransactionScope[] | Prisma.ListEnumTransactionScopeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumTransactionScopeNullableWithAggregatesFilter<$PrismaModel> | $Enums.TransactionScope | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTransactionScopeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTransactionScopeNullableFilter<$PrismaModel>
}

export type NestedEnumBusinessFormNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BusinessForm | Prisma.EnumBusinessFormFieldRefInput<$PrismaModel> | null
  in?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.BusinessForm[] | Prisma.ListEnumBusinessFormFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumBusinessFormNullableWithAggregatesFilter<$PrismaModel> | $Enums.BusinessForm | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBusinessFormNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBusinessFormNullableFilter<$PrismaModel>
}

export type NestedEnumOfferTypeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.OfferType | Prisma.EnumOfferTypeFieldRefInput<$PrismaModel> | null
  in?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.OfferType[] | Prisma.ListEnumOfferTypeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumOfferTypeNullableWithAggregatesFilter<$PrismaModel> | $Enums.OfferType | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumOfferTypeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumOfferTypeNullableFilter<$PrismaModel>
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}


