
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const VehicleKpp = {
  Variable: 'Variable',
  Automatic: 'Automatic',
  Manual: 'Manual',
  Robot: 'Robot'
} as const

export type VehicleKpp = (typeof VehicleKpp)[keyof typeof VehicleKpp]


export const PaymentType = {
  Full: 'Full',
  Trade: 'Trade',
  Mortgage: 'Mortgage',
  InstallmentPlan: 'InstallmentPlan'
} as const

export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType]


export const HouseState = {
  CosmeticRepairs: 'CosmeticRepairs',
  EuroRepairs: 'EuroRepairs',
  RoughFinish: 'RoughFinish',
  NeedRepairs: 'NeedRepairs'
} as const

export type HouseState = (typeof HouseState)[keyof typeof HouseState]


export const PropertyType = {
  Panel: 'Panel',
  Brick: 'Brick',
  Monolith: 'Monolith'
} as const

export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType]


export const Cooling = {
  Air: 'Air',
  Liquid: 'Liquid'
} as const

export type Cooling = (typeof Cooling)[keyof typeof Cooling]


export const Employment = {
  FullTime: 'FullTime',
  PartTime: 'PartTime',
  Temporary: 'Temporary',
  Internship: 'Internship'
} as const

export type Employment = (typeof Employment)[keyof typeof Employment]


export const WorkFormat = {
  Outsource: 'Outsource',
  Office: 'Office',
  Hybride: 'Hybride'
} as const

export type WorkFormat = (typeof WorkFormat)[keyof typeof WorkFormat]


export const PriceFor = {
  Service: 'Service',
  Hour: 'Hour',
  Day: 'Day',
  Week: 'Week',
  Month: 'Month'
} as const

export type PriceFor = (typeof PriceFor)[keyof typeof PriceFor]


export const Drive = {
  Full: 'Full',
  Rear: 'Rear',
  Front: 'Front'
} as const

export type Drive = (typeof Drive)[keyof typeof Drive]


export const SteeringWheel = {
  DoesntMatter: 'DoesntMatter',
  Left: 'Left',
  Right: 'Right'
} as const

export type SteeringWheel = (typeof SteeringWheel)[keyof typeof SteeringWheel]


export const VesselType = {
  Boat: 'Boat',
  MotorYacht: 'MotorYacht',
  SailingYacht: 'SailingYacht',
  Vessels: 'Vessels'
} as const

export type VesselType = (typeof VesselType)[keyof typeof VesselType]


export const TransactionScope = {
  Meet: 'Meet',
  Sell: 'Sell',
  FindPartner: 'FindPartner'
} as const

export type TransactionScope = (typeof TransactionScope)[keyof typeof TransactionScope]


export const BusinessForm = {
  IE: 'IE',
  LLC: 'LLC',
  JSC: 'JSC',
  Other: 'Other'
} as const

export type BusinessForm = (typeof BusinessForm)[keyof typeof BusinessForm]


export const OfferType = {
  Tour: 'Tour',
  Excursion: 'Excursion',
  WeekendTour: 'WeekendTour',
  SignatureTour: 'SignatureTour',
  Transfer: 'Transfer',
  HousingRental: 'HousingRental',
  Travel: 'Travel'
} as const

export type OfferType = (typeof OfferType)[keyof typeof OfferType]
